server:
  port: 8081
constant:
   icourse163Url: http://www.icourse163.org
spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.150:3306/ncvt?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: yunXin!63#
